# Generated by Django 6.0.1 on 2026-02-03 11:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Nombre del cliente')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email del cliente')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Teléfono del cliente')),
                ('reservation_date', models.DateField(verbose_name='Fecha de reservación')),
                ('reservation_time', models.TimeField(verbose_name='Hora de reservación')),
                ('num_people', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de personas')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='Solicitudes especiales')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada'), ('completed', 'Completada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='availability.restaurant', verbose_name='Restaurante')),
            ],
            options={
                'verbose_name': 'Reservación',
                'verbose_name_plural': 'Reservaciones',
                'ordering': ['reservation_date', 'reservation_time'],
                'indexes': [models.Index(fields=['restaurant', 'reservation_date'], name='reservation_restaur_d27b89_idx'), models.Index(fields=['customer_email'], name='reservation_custome_f4fe2a_idx')],
            },
        ),
    ]
